[package]
name = "libzip_rs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-compression.workspace = true
async-fn-stream.workspace = true
fastsearch.workspace =  true
indexmap.workspace = true
rayon.workspace = true
smol.workspace = true

